apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mergeown-sub
  namespace: rootsub
  annotations:
    apps.open-cluster-management.io/reconcile-option: mergeAndOwn
    apps.open-cluster-management.io/git-path: mergeown
    apps.open-cluster-management.io/git-branch: test-branch
spec:
  channel: rootsub/rootchannel
  placement:
    placementRef:
      name: dev-cluster-root