apiVersion: apps.open-cluster-maxnagement.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-cluster-test
  namespace: default
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: argocdtest1
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1alpha1
    name: test-placement
    namespace: default